services:
  master:
    build:
      dockerfile: Dockerfile
      context: master
    networks:
      - master_slave
  
  slave:
    build:
      dockerfile : Dockerfile
      context: slave
    networks:
      - master_slave
      - cache
    volumes:
      - slave_exports:/exports
    depends_on:
      - redis_cache
      - master
    environment:
      - SLAVE_ID=1
      - MASTER_URL=http://master:3000
      - REDIS_HOSTNAME=redis_cache
      - OUTPUT_PATH=/exports
      - MAX_NB_TREATED=2
    
  redis_cache:
    image: redis
    networks:
      - cache

networks:
  cache:
  master_slave:

volumes:
  slave_exports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: results
